services:
  api:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/api
    command: "npm run start:dev"
    networks: 
      - backend
  postgres:
    container_name: database
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - backend
networks:
  backend: 